sudo: required
services:
  - docker

before_install:
  - docker build -t denysisaievsbtech/docker-react -f Dockerfile.dev .

script:
  - docker run denysisaievsbtech/docker-react npm run test -- --coverage

deplouy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-578948455705"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: "Dat8RGtEfMzr1V2frRus+gwjqBDURaF8rOHPTBxRXe5/axPYaEiHeb2ufiE6Tq4qcYIf4vVWLFZ/ejr/+PpG3og8zD705DeULjNg00dS9+rw+BNL9zyfGCBlwaj4SuK02zOLxrVescQAiE6TTgDdQqSLfrO0KEKZNVr2Kv7kGQ/dGbPYSWSmQpvx6k46A4tqNFLJ2uD4pdqFEtTGQN52hZkk1C7DUlkbnPcBMhkH/vuLuAW8Ah81i1poCqxu/05VNCWE9uq8XNN2V5nhcKEksSmsF8wGXMkvmCwxT0AHh/zyX3GQZEI7zmSfFqhvIRFSY08JGd6FYVylyYg4iFjBgHZFpmBG68sEAVO82Kd0OejLR+zcrpNurpD3vtZ/ZOK6aCvIg3IdJGwyTsOjhx8Y1UNlaOXLyA6II+MeKi4WFJlJjvBk7AtGTmH1M/hjuSFoDx3Gh0gct0r/F8mcxZhiduB6bCrGdCSZQ0Q23Kj9HwzpYiSb5dEvF/KM6hizdIcq4fZMwu8Vw5dMcckgB3xdJOqDVMxb8fIzoYhdUigzXX4r2/CZCXoIa3hgBBYgZr6qn3H6m9aZCoks/Q/qGBq6qi5vSK/eOVvLZOZZPrxaXIAwegMabEmecaIltUSARvxq2SQ5yDo/rajmMpBE5Nl8yEXsGBB7UVnMVRk9W/nrgSo="
  secret_access_key:
    secure: "Q8hyK+kosulLpgKT1WG6zINiqckupbd1my2q4dGwKZlurxriFzlIqiwIRtibr7tz66J9FhjryE3xRCPGb4YDLD4bm/UEhdGZ8YOLO8oeURjr3M9nWeusNAfoLDDmYtCCIpFagYFdCySW5e94ZsGpOC+9lrs/sQNfnp/FvPlpE8+YEeVPth2cWv3mgR32gh79XsRDWxP1+B7CnQZtXBVIzPXr3dX452ePS+GJ5z+VwA6Co5K1S1zfQnG4GOqHFgvT/4/J5sAl6lBN7PAt0/qv8Fo01HVp44GCLVJUIfdExtB8ivrSgI5i6kuDuk02VUIicm8ARSpIpHrMTej/xGzXkG0b4+g+9UKStCHK7gfRA5IkqZnZlNDp3XDnsG+q6AlkwiMXmNBRquVDfHK9OCakWrl0XozqTidO59FWGTgVLCxBlwaMOHPx2JZe2Bih39woTqLDLuoR4hu3hdYEYT0rFBG3BVim6KU+up7yqpd7L7gSHe3sOcrw0CO8NrmpI9XSIxTvqvxFbu9O2iDUMUHP8cmQTJqVKfjkytqlMK5b6nEEQwgfk60V5VFzJ7/kTLo0UBi+NS4zZ3KafDcVqbGeju3/05Sp52w5+9p+PueQGsK0Bnez35pxVjUt99wAkWl0p1yK1B7SScurZaxF1FZsoGmhl7yoasylurUL/RpWUFk="