sudo: required
services:
  - docker

before_install:
  - docker build -t denysisaievsbtech/docker-react -f Dockerfile.dev .

script:
  - docker run denysisaievsbtech/docker-react npm run test -- --coverage

deplouy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-578948455705"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY"