sudo: required

env:
  global:
    secure: ByKarE8TLrj1vZa0hX7aPTGTsXDNPx9z3rNsOC38aDZqCHYPTjAbxQtUwDsBjp/dIqwCPF0E0NMjkLF3jJAI5ojjA+NVyngBYW8Nkgy+erbrY8sybfkp3zAubD1K6OOaV7tFhjYkNxfcS7cvbDzdlObOLqi5X96ZUXrAH3ZiOvUDGsPF++5xJRats5FyGzYN4wJi/64ZiDVWvO1HrIEoMjn3c2ARC+3H5O3i9AQ9ok0q+iHcRsiz1nF49e0ffW8PuXunrYk9xztYfq4kOr08GEEZzv+Ayx+OEi3Q7Uhm+9PB/XY1dJs5y4mv/Zi+BEPDsiJkqJ1uHj2dqtfqeZE+qdCR5tf2VjAq8WFWznSWvKsrl4JqiSsIsmyy2wr0yHi0NhK/NzkVyWh8VZbZ9etf86FhqcU66gkSHQ9lJDsmTCrNr98SR4JZlh7zshgHZ1fYUg18IrfLxs1CWO6QVO+Y+1yf3SNCsHWqqvwHtv7BXKvArlUtNprbP+D6u23hBOxwq60sb9EX31I/kvJ0qHmYykutygDj0IZEaMeBRNiQsmHlUyTL/J2hR8A6R6r69ty5G2PfI2xPj0LNzpbWUw3qVHrb7ch1i3PxAxRdtfouGQkktOwF8VEc1RBnWXP442eDJ5KrQGxqxsVMNf/3+OXq2XUVGpn+cu/NJAsh2YQJ700=
dd:
  secure: gTVdVpA7srvQrMNTZUxO5JNlTe/rmifAorr08FE1IwsUNb91Cx4LUphg2Qi/bDRPfYSMBtqrR1xJpjPLUZ/EvykEeN5YE0y05XCqZqxuokbTX59/eAC+U0qa8foaiY6p+O/hqlB0elqL8ZhytuoLup5tO2A934TWYYp08PW8Wut5lSarVjMzABT9CQaa4LoJDMvh6flCAe2qiU6bGQJo0DCyF7daAbB1mYXLrByS1tFFLC+CDtjz8Dv0RO2qddXsw0PizQBkHFLOcrbMgvTHwhs5m5GT2oiv9x9NZ/SRcIJcXDO1YtxLNX/BVWx7tN0AE8FB76VBs8539jgPfeRmTkc/0iPvWBJrRk0sA4DolLPImAh71VYvvuc91Y7dPgmstAl/nXLSO+veICjHhxG/Mw2BXh7unfnKn5GPnQBXQIkjGsW5crb9t3QIIV9ksD+zHapr7nLky7ftYyyvAdqJih31Ga7Y2jqP9GHp4FGgDdI4hyEdHa8RIYkQAaNEQkYUY/Uar9R/P+iefPQHQ14duCNcEG6U+rUy0t83FArg8m+mmxpDp6k5Ex4k1WQEOQMkoVAMKzExbEJIVDce9GrfODR9277L/eewZhEqnBpTeaX5OGVy7ZRqQxR+JvhXinsFORLooc/ZcwxDyHzQAkz0Hug+jY/eB8ugppvzQUgYb3w=

services:
- docker

before_install:
- docker build -t denysisaievsbtech/docker-react -f Dockerfile.dev .
script:
- docker run denysisaievsbtech/docker-react npm run test -- --coverage
- echo $AWS_ACCESS_KEY
- echo $AWS_SECRET_KEY

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-578948455705"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY